name: Test Build exampleSite

on:
  push:
    branches:
      - main

jobs:
  build-deploy: 
    name: Test Build exampleSite
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.119.0"
          extended: true
          
      - name: Build
        working-directory: ./exampleSite
        run: hugo --minify --themesDir ../.. --baseURL https://chrede88.github.io/L1nkr/